apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # argocd with argocd-lovelvy und vault plugin
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.7.1

  # argocd projects & applicationssets
  - ./manifests/

patches:
  # install argocd-lovely-plugin
  - path: patches/argocd-lovely-plugin.yaml
    target:
      kind: Deployment
      name: argocd-repo-server

  # Add tolerations to Deployment resources
  - path: patches/add-tolerations.yaml
    target:
      name: .*
      kind: Deployment

  # Add tolerations to DaemonSet resources
  - path: patches/add-tolerations.yaml
    target:
      name: .*
      kind: DaemonSet

  # Add tolerations to StatefulSet resources
  - path: patches/add-tolerations.yaml
    target:
      name: .*
      kind: StatefulSet
