apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # argocd with argocd-lovelvy und vault plugin
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.7.1

  # argocd projects & applicationssets
  - ./manifests/

patches:
  # install argocd-vault-replacer
  - path: patches/argocd-vault-replacer.yaml
    target:
      kind: Deployment
      name: argocd-repo-server

  - path: patches/disable-tls.yaml
  - path: patches/add-tolerations.yaml
    target:
     name: .*
     kind: (Deployment|DaemonSets|StatefulSets)
