apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
# argocd with argocd-lovelvy und vault plugin
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.5/manifests/ha/install.yaml

# argocd projects & applicationssets
- ./manifests/

patches:
  - path: patches/argo-cm.yaml
  - path: patches/argocd-lovely-plugin.yaml
  - path: patches/argocd-vault-replacer.yaml

  - path: patches/disable-tls.yaml

  - path: patches/add-tolerations.yaml
    target:
     name: .*
     kind: (Deployment|DaemonSets|StatefulSets)
