apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hosterei-base
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/hosterei/tools.git
      revision: main
      pathParamPrefix: "base"
      directories:
      - path: base/*
  template:
    metadata:
      name: '{{base.path.basename}}'
    spec:
      project: "hosterei-local"
      source:
        repoURL: https://github.com/hosterei/tools.git
        targetRevision: main
        path: '{{base.path}}'
        plugin:
          name: argocd-lovely-plugin
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{base.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
        syncOptions:
        - CreateNamesapce=true
        
