apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hosterei-mgmt
  namespace: argocd
spec:
  generators:
  - merge:
      mergeKeys:
        - path.basename
      generators:
      - git: # base repo
          repoURL: https://github.com/hosterei/tools.git
          revision: main
          directories:
          - path: base/*
      - git: # mgmt overlay repo
          repoURL: https://github.com/hosterei/tools.git
          revision: main
          directories:
          - path: overlays/mgmt/*
      
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: "hosterei-local"
      source:
        repoURL: https://github.com/hosterei/tools.git
        targetRevision: main
        path: '{{path}}'
        plugin:
          name: argocd-lovely-plugin-v1.0
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
        
